import React from 'react';
import { makeStyles, Typography, Card } from '@material-ui/core';

const useStyles = makeStyles(theme => ({
    root: {
        backgroundColor: '#87CEFA',        
        marginTop: "60px"
    },
    cardStyle: { height: "100%", width: "100%", backgroundColor: '#87CEFA' },
    descriptionStyle: { textAlign: "center", color: "green", fontWeight: 900, fontSize: "25px" },
    aboutus: { paddingLeft:"50px", paddingRight:"50px",paddingTop:"10px", textAlign: "justify", color: "black", fontWeight: 400, fontSize: "20px" },
    headingStyle: { textAlign: "center", color: "green", fontWeight: 900, fontSize: "50px", paddingTop: "5px" },
    aboutusHeading: {paddingLeft:"50px",paddingTop:"10px", textAlign: "left", color: "black", fontWeight: 900, fontSize: "26px"},
    displayFlex: {display:'flex'},
    aboutusDescription: { paddingRight:"30px",paddingTop:"19px", textAlign:"justify"},
    listStyle: {textAlign:"left", paddingLeft:"50px", fontSize:"20px"}
}));

const AboutUs = () => {
    const classes = useStyles();

    return (
        <div className={classes.root}>
            <Card className={classes.cardStyle}>
                <Typography className={classes.headingStyle}>Welcome to Electricaltrendz</Typography>
                <Typography className={classes.descriptionStyle}> This is the place where you will get all kind of solar solution.</Typography>
                <Typography className={classes.descriptionStyle}>Complete SOLAR solution under single roof.</Typography>

                <Typography className={classes.aboutus}>
                    Electricaltrendz is a fully forward- integrated and comprehensive EPC solution provider. We have skilled and dedicated EPC team to ensure the completion of work. Our dedicated teams work in strong cohesion to deliver customized solution to our dedicated customers keeping a delivery focused approach and excellence as the crux of our initiative. We never compromise with our commitment.
                </Typography>
                <br></br>
                <Typography className={classes.aboutusHeading}>We provide many services under solar power generating system (SPGS)</Typography>
                <div className={classes.displayFlex}>
                <Typography className={classes.aboutusHeading}>Off-grid photovoltaic system-</Typography>
                <Typography className={classes.aboutusDescription}>In this system the excess energy generated from the solar (PV) system is charge the battery and use it later.</Typography>
                </div>
                <br></br>
                <br></br>
                <div className={classes.displayFlex}>
                <Typography className={classes.aboutusHeading}>Grid tied (on-grid) system-</Typography>
                <Typography className={classes.aboutusDescription}>In this system the excess energy generated form solar (PV) system may sell to DISCOM through utility grid.</Typography>
                </div>
                <br></br>
                <br></br>
                <div className={classes.displayFlex}>
                <Typography className={classes.aboutusHeading}>SolarPump-</Typography>
                <Typography className={classes.aboutusDescription}>this system is used for irrigation purpose, submersible pump used electricity which is generated by solar modules.it is more economical than diesel, wind and utility grid. </Typography>
                </div>
                <br></br>
                <br></br>
                <Typography className={classes.aboutusHeading}>Our design criteria of any project are based on eight parameters-</Typography><br></br>
                <li className={classes.listStyle}>Budget</li><br></br>
                <li className={classes.listStyle}>Power quality</li><br></br>
                <li className={classes.listStyle}>Environmental impact</li><br></br>
                <li className={classes.listStyle}>Aesthetics</li><br></br>
                <li className={classes.listStyle}>Noise level</li><br></br>
                <li className={classes.listStyle}>Site accessibility</li><br></br>
                <li className={classes.listStyle}>Level of automation</li><br></br>
                <li className={classes.listStyle}>Customer satisfaction</li><br></br>
            </Card>
        </div>
    )
}

export default AboutUs;
